### ISSUE TITLE
Outstanding Items

### ISSUE THREAD

**Issue by Mr-Dave** [Motion-Project/motionplus#13]
- [ ] Resolve/fix latency on some cameras
- [ ] Resolve/fix the sound processing
- [ ] Resolve/fix the extra short videos
- [x] Web interface - Better process for more than 6 cameras
- [ ] Web interface - Show recordings and information about them
- [x] Web interface - Select and play recordings
- [ ] Convert modules to C++
- [x] Interface to libcamera?
- [ ] Enhance OpenCV processing and add AI/ML available in OpenCV 4
- [ ] Rewrite documentation

**Comment by kbingham** [comment]
Happy to help supporting the implementation of a libcamera input module.

**Comment by Mr-Dave** [comment]
At this time of the year my development time is pretty limited but if you'd like to put together a module, that would be good.  The most straight forward template is mmalcam.cpp.

**Comment by Mr-Dave** [comment]
Closing to track offline.  Initial revision for libcamera implemented.

**Comment by GenerallyClumsy** [comment]
Hey team, I'm trying to get things setup with libcamera but the documentation is not ready for that part. Any tips on how to get started?

**Comment by Mr-Dave** [comment]
You are correct, I missed that in my rewritten instructions.  

Specify `libcam_name camera0` in the configuration parameters and it will use the libcamera functionality directly instead of needing the `libcamerify`  

Nothing has been implemented for libcam_params so that parameter is ignored for now until I can figure out how to implement any camera parameters that libcamera may expose.

The libcam support (or lack thereof) will be reported in the last status message section of the configure.

**Comment by mckin21** [comment]
Hello! I wanted to just tack only this thread rather than make a new issue. I'm trying to get the Raspberry Pi V3 cam to run with Motion/Motionplus on raspbian bullseye. Something in the libcamera-tools package consistently breaks libcamera so I wanted to try motionplus. I've set up motionplus but I am not getting any video detection or movie files saved. 
Here is my log file at log level 9:
`Feb 16 20:14:29 [NTC][ALL][00:motionplus] log_init: MotionPlus 0.0.0-git-20230206-90bb157 started
Feb 16 20:14:29 [NTC][ALL][00:motionplus] log_init: Using log type (ALL) log level (ALL)
Feb 16 20:14:29 [NTC][ALL][00:motionplus] mytranslate_init: Language: English
Feb 16 20:14:29 [INF][ALL][00:motionplus] conf_parms_log: Logging configuration parameters from all files
Feb 16 20:14:29 [INF][ALL][00:motionplus] Config file: /etc/motionplus/motionplus.conf
Feb 16 20:14:29 [INF][ALL][00:motionplus] daemon                    off
Feb 16 20:14:29 [INF][ALL][00:motionplus] setup_mode                off
Feb 16 20:14:29 [INF][ALL][00:motionplus] pid_file                  
Feb 16 20:14:29 [INF][ALL][00:motionplus] log_file                  /home/pi/motionplus.log
Feb 16 20:14:29 [INF][ALL][00:motionplus] log_level                 9
Feb 16 20:14:29 [INF][ALL][00:motionplus] log_type                  ALL
Feb 16 20:14:29 [INF][ALL][00:motionplus] native_language           on
Feb 16 20:14:29 [INF][ALL][00:motionplus] device_name               
Feb 16 20:14:29 [INF][ALL][00:motionplus] device_id                 0
Feb 16 20:14:29 [INF][ALL][00:motionplus] device_tmo                30
Feb 16 20:14:29 [INF][ALL][00:motionplus] pause                     off
Feb 16 20:14:29 [INF][ALL][00:motionplus] target_dir                /home/pi/motionplusmedia
Feb 16 20:14:29 [INF][ALL][00:motionplus] watchdog_tmo              30
Feb 16 20:14:29 [INF][ALL][00:motionplus] watchdog_kill             10
Feb 16 20:14:29 [INF][ALL][00:motionplus] v4l2_device               
Feb 16 20:14:29 [INF][ALL][00:motionplus] v4l2_params               
Feb 16 20:14:29 [INF][ALL][00:motionplus] netcam_url                <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] netcam_params             
Feb 16 20:14:29 [INF][ALL][00:motionplus] netcam_high_url           <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] netcam_high_params        
Feb 16 20:14:29 [INF][ALL][00:motionplus] netcam_userpass           <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] libcam_device             camera0
Feb 16 20:14:29 [INF][ALL][00:motionplus] libcam_params             
Feb 16 20:14:29 [INF][ALL][00:motionplus] width                     320
Feb 16 20:14:29 [INF][ALL][00:motionplus] height                    240
Feb 16 20:14:29 [INF][ALL][00:motionplus] framerate                 15
Feb 16 20:14:29 [INF][ALL][00:motionplus] rotate                    0
Feb 16 20:14:29 [INF][ALL][00:motionplus] flip_axis                 none
Feb 16 20:14:29 [INF][ALL][00:motionplus] locate_motion_mode        off
Feb 16 20:14:29 [INF][ALL][00:motionplus] locate_motion_style       box
Feb 16 20:14:29 [INF][ALL][00:motionplus] text_left                 CAMERA1
Feb 16 20:14:29 [INF][ALL][00:motionplus] text_right                %Y-%m-%d\n%T-%q
Feb 16 20:14:29 [INF][ALL][00:motionplus] text_changes              off
Feb 16 20:14:29 [INF][ALL][00:motionplus] text_scale                1
Feb 16 20:14:29 [INF][ALL][00:motionplus] text_event                %Y%m%d%H%M%S
Feb 16 20:14:29 [INF][ALL][00:motionplus] emulate_motion            off
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold                 1500
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_maximum         0
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_sdevx           0
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_sdevy           0
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_sdevxy          0
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_ratio           0
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_ratio_change    64
Feb 16 20:14:29 [INF][ALL][00:motionplus] threshold_tune            off
Feb 16 20:14:29 [INF][ALL][00:motionplus] secondary_method          none
Feb 16 20:14:29 [INF][ALL][00:motionplus] secondary_params          
Feb 16 20:14:29 [INF][ALL][00:motionplus] noise_level               32
Feb 16 20:14:29 [INF][ALL][00:motionplus] noise_tune                on
Feb 16 20:14:29 [INF][ALL][00:motionplus] despeckle_filter          EedDl
Feb 16 20:14:29 [INF][ALL][00:motionplus] area_detect               
Feb 16 20:14:29 [INF][ALL][00:motionplus] mask_file                 
Feb 16 20:14:29 [INF][ALL][00:motionplus] mask_privacy              
Feb 16 20:14:29 [INF][ALL][00:motionplus] smart_mask_speed          0
Feb 16 20:14:29 [INF][ALL][00:motionplus] lightswitch_percent       0
Feb 16 20:14:29 [INF][ALL][00:motionplus] lightswitch_frames        5
Feb 16 20:14:29 [INF][ALL][00:motionplus] minimum_motion_frames     1
Feb 16 20:14:29 [INF][ALL][00:motionplus] static_object_time        10
Feb 16 20:14:29 [INF][ALL][00:motionplus] event_gap                 60
Feb 16 20:14:29 [INF][ALL][00:motionplus] pre_capture               3
Feb 16 20:14:29 [INF][ALL][00:motionplus] post_capture              0
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_event_start            
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_event_end              
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_picture_save           
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_area_detected          
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_motion_detected        
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_movie_start            
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_movie_end              
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_camera_lost            
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_camera_found           
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_secondary_detect       
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_action_user            
Feb 16 20:14:29 [INF][ALL][00:motionplus] on_sound_alert            
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_output            off
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_output_motion     off
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_type              jpeg
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_quality           75
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_exif              
Feb 16 20:14:29 [INF][ALL][00:motionplus] picture_filename          %Y%m%d%H%M%S-%q
Feb 16 20:14:29 [INF][ALL][00:motionplus] snapshot_interval         0
Feb 16 20:14:29 [INF][ALL][00:motionplus] snapshot_filename         %v-%Y%m%d%H%M%S-snapshot
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_output              on
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_output_motion       off
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_max_time            60
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_bps                 400000
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_quality             45
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_container           mp4
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_passthrough         off
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_filename            %t-%v-%Y%m%d%H%M%S
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_retain              all
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_extpipe_use         off
Feb 16 20:14:29 [INF][ALL][00:motionplus] movie_extpipe             
Feb 16 20:14:29 [INF][ALL][00:motionplus] timelapse_interval        0
Feb 16 20:14:29 [INF][ALL][00:motionplus] timelapse_mode            daily
Feb 16 20:14:29 [INF][ALL][00:motionplus] timelapse_fps             30
Feb 16 20:14:29 [INF][ALL][00:motionplus] timelapse_container       mpg
Feb 16 20:14:29 [INF][ALL][00:motionplus] timelapse_filename        %Y%m%d-timelapse
Feb 16 20:14:29 [INF][ALL][00:motionplus] video_pipe                
Feb 16 20:14:29 [INF][ALL][00:motionplus] video_pipe_motion         
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_port           8080
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_base_path      
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_ipv6           off
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_localhost      off
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_parms          0
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_interface      default
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_auth_method    none
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_authentication <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_tls            off
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_cert           <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_key            <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_headers        
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_html           
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_actions        
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_lock_minutes   10
Feb 16 20:14:29 [INF][ALL][00:motionplus] webcontrol_lock_attempts  3
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_preview_scale      25
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_preview_newline    off
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_preview_method     mjpg
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_preview_ptz        on
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_quality            50
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_grey               off
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_motion             off
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_maxrate            1
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_scan_time          5
Feb 16 20:14:29 [INF][ALL][00:motionplus] stream_scan_scale         25
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_type             
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_dbname           
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_host             
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_port             0
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_user             <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_password         <redacted>
Feb 16 20:14:29 [INF][ALL][00:motionplus] database_busy_timeout     0
Feb 16 20:14:29 [INF][ALL][00:motionplus] sql_event_start           
Feb 16 20:14:29 [INF][ALL][00:motionplus] sql_event_end             
Feb 16 20:14:29 [INF][ALL][00:motionplus] sql_movie_start           
Feb 16 20:14:29 [INF][ALL][00:motionplus] sql_movie_end             
Feb 16 20:14:29 [INF][ALL][00:motionplus] sql_pic_save              
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_auto_track            off
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_wait                  0
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_move_track            
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_pan_left              
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_pan_right             
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_tilt_up               
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_tilt_down             
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_zoom_in               
Feb 16 20:14:29 [INF][ALL][00:motionplus] ptz_zoom_out              
Feb 16 20:14:29 [INF][ALL][00:motionplus] snd_device                
Feb 16 20:14:29 [INF][ALL][00:motionplus] snd_params                
Feb 16 20:14:29 [INF][ALL][00:motionplus] snd_window                hamming
Feb 16 20:14:29 [INF][ALL][00:motionplus] snd_show                  off
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: v4l2   : available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: webp   : available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: libcam : not available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: mysql  : not available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: MariaDB: available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: sqlite3: not available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: pgsql  : not available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: nls    : available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: alsa   : available
Feb 16 20:14:29 [DBG][ALL][00:motionplus] motpls_ntc: fftw3  : available
Feb 16 20:14:29 [NTC][STR][00:motionplus] webu_init_webcontrol: Starting webcontrol on port 8080
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >event< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >snapshot< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >pause< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >restart< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >stop< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >config_write< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >camera_add< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >camera_delete< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >config< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >ptz< >off<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >movies< >on<
Feb 16 20:14:29 [INF][ALL][00:motionplus] util_parms_add: Parsed: >action_user< >off<
Feb 16 20:14:29 [DBG][STR][00:motionplus] webu_mhd_features_basic: Basic authentication: available
Feb 16 20:14:29 [DBG][STR][00:motionplus] webu_mhd_features_digest: Digest authentication: available
Feb 16 20:14:29 [DBG][STR][00:motionplus] webu_mhd_features_ipv6: IPV6: available
Feb 16 20:14:29 [DBG][STR][00:motionplus] webu_mhd_features_tls: SSL/TLS: available
Feb 16 20:14:29 [NTC][STR][00:motionplus] webu_init_webcontrol: Started webcontrol on port 8080
Feb 16 20:14:29 [NTC][ENC][00:motionplus] movie_global_init: libavcodec  version 58.91.100
Feb 16 20:14:29 [NTC][ENC][00:motionplus] movie_global_init: libavformat version 58.45.100
Feb 16 20:14:29 [NTC][ALL][00:motionplus] main: Motionplus pid: 974
Feb 16 20:14:44 [NTC][ALL][00:motionplus] main: Motionplus devices finished
Feb 16 20:14:44 [NTC][ALL][00:motionplus] main: MotionPlus terminating
Feb 16 20:14:44 [NTC][ALL][00:motionplus] log_deinit: Closing logfile (/home/pi/motionplus.log).`

Here is my configuration file:
`
# Start in daemon (background) mode and release terminal.
daemon off

# Start in Setup-Mode, daemon disabled.
setup_mode off

# File to store the process ID.
; pid_file value

# File to write logs messages into.  If not defined stderr and syslog is used.
log_file /home/pi/motionplus.log

# Level of log messages [1..9] (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL).
log_level 9

# Target directory for pictures, snapshots and movies
target_dir /home/pi/motionplusmedia

# Video device (e.g. /dev/video0) to be used for capturing.
libcam_device camera0


############################################################
# Image Processing configuration parameters
############################################################

# Image width in pixels.
width 320

# Image height in pixels.
height 240

# Maximum number of frames to be captured per second.
framerate 15

# Text to be overlayed in the lower left corner of images
text_left CAMERA1

# Text to be overlayed in the lower right corner of images.
text_right %Y-%m-%d\n%T-%q

############################################################
# Motion detection configuration parameters
############################################################

# Always save pictures and movies even if there was no motion.
emulate_motion off

# Threshold for number of changed pixels that triggers motion.
threshold 1500

# Noise threshold for the motion detection.
; noise_level 32

# Despeckle the image using (E/e)rode or (D/d)ilate or (l)abel.
despeckle_filter EedDl

# Number of images that must contain motion to trigger an event.
minimum_motion_frames 1

# Gap in seconds of no motion detected that triggers the end of an event.
event_gap 60

# The number of pre-captured (buffered) pictures from before motion.
pre_capture 3

# Number of frames to capture after motion is no longer detected.
post_capture 0

############################################################
# Script execution configuration parameters
############################################################

# Command to be executed when an event starts.
; on_event_start value

# Command to be executed when an event ends.
; on_event_end value

# Command to be executed when a movie file is closed.
; on_movie_end value

############################################################
# Picture output configuration parameters
############################################################

# Output pictures when motion is detected
picture_output off

# File name(without extension) for pictures relative to target directory
picture_filename %Y%m%d%H%M%S-%q

############################################################
# Movie output configuration parameters
############################################################

# Create movies of motion events.
movie_output on

# Maximum length of movie in seconds.
movie_max_time 60

# The encoding quality of the movie. (0=use bitrate. 1=worst quality, 100=best)
movie_quality 45

# Container/Codec to used for the movie. See motion_guide.html
movie_container mp4

# File name(without extension) for movies relative to target directory
movie_filename %t-%v-%Y%m%d%H%M%S

############################################################
# Webcontrol configuration parameters
############################################################

# Port number used for the webcontrol.
webcontrol_port 8080

# Restrict webcontrol connections to the localhost.
webcontrol_localhost off

# Type of configuration options to allow via the webcontrol.
webcontrol_parms 0

##############################################################
# Camera config files - One for each camera.
##############################################################

##############################################################
# Directory to read '.conf' files for cameras.
##############################################################
`
I've used a similar (obviously not updated for motionplus parameters) configuration file with motion and the raspberry pi V2 camera on raspbian buster with the legacy camera stack to ensure that I could get the base motion configurations running. 

I can see that, under the current build, it states `libcamera support     : no`. Does this mean that libcamera cannot run with motionplus at all, or just without video parameters? Will motion with `libcamerify` be my only option, or should I just get a difference camera?
