### ISSUE TITLE
git head compile fail in webu_mpegts.cpp

### ISSUE THREAD

**Issue by gene-git** [Motion-Project/motionplus#138]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.1.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Other

### Disto version number

Arch linux

### Camera/Sound type(s) being used?

Network camera with RTSP, Other

### Describe the issue/problem and steps to reproduce

FYI

After commit 3efa0d36de2c9e4add49d6ee4dbd78c9329dba7d build fails here:

```
webu_mpegts.cpp: In function ‘int webu_mpegts_open(ctx_webui*)’:
webu_mpegts.cpp:366:17: error: invalid conversion from ‘int (*)(void*, myuint*, int)’ {aka ‘int (*)(void*, const unsigned char*, int)’} to ‘int (*)(void*, uint8_t*, int)’ {aka ‘int (*)(void*, unsigned char*, int)’} [-fpermissive]
  366 |         , NULL, &webu_mpegts_avio_buf, NULL);
      |                 ^~~~~~~~~~~~~~~~~~~~~
      |                 |
      |                 int (*)(void*, myuint*, int) {aka int (*)(void*, const unsigned char*, int)}
```

Using gcc 13.2.1
Arch Linux

### Relevant MotionPlus log output (at log_level 8)

```shell
N/A
```

**Comment by Mr-Dave** [comment]
Do you know the avformat version?

**Comment by gene-git** [comment]
ffmpeg is 
``
Version         : 6.1.1
```

from libavformat/version_major.h
```
#define LIBAVFORMAT_VERSION_MAJOR  60
```

from libavformat/version.h
```
#define LIBAVFORMAT_VERSION_MINOR  16
#define LIBAVFORMAT_VERSION_MICRO 100
```

**Comment by gene-git** [comment]
is that what you 're looking for or something else?

**Comment by Mr-Dave** [comment]
Yes that is it.

Seems like the documentation is just slightly off in ffmpeg.  The [FFmpeg 6.1 documentation](https://ffmpeg.org/doxygen/6.1/avio_8h.html#a50c588d3c44707784f3afde39e1c181c) shows it wanting a `const` while the [FFmpeg 6.0 documentation](https://ffmpeg.org/doxygen/6.0/avio_8h.html#a853f5149136a27ffba3207d8520172a5) doesn't.  And your 6.1 obviously doesn't want a const since it doesn't compile....I'll push a change to criteria ..

**Comment by gene-git** [comment]
Thank you!
It is now building fine.
