### ISSUE TITLE
Motionplus get stuck in "answer_get: processing get" and has to be kill -9 handled

### ISSUE THREAD

**Issue by sroller** [Motion-Project/motionplus#188]
### Did you read the guide?

Yes

### What is the base version number of MotionPlus being used?

0.2.x

### What was the install method?

Built from source code

### What is base architecture?

x86/x64

### What is the distro being used?

Ubuntu

### Disto version number

24.04.1

### Camera/Sound type(s) being used?

Network camera with RTSP

### Describe the issue/problem and steps to reproduce

I have a network with a central x86 based motionplus on Ubuntu and 3 Raspberry Pi with picam v1, v2 and v3.
On the Ubuntu server runs nginx with rtmp module.
I can stream from all 3 RPis to the server. I can run on a Windows PC three ffplay instances at the same time which show all streams.
That should show, that the streaming infrastructure should be ok.

I doesn't work with MP though. I could get it going with 2 cameras at some point in time. But the third led to the crash. Switching off some of the cameras didn't work either.
When I'm trying to select  one of the cameras the webpage hangs and the server enters an endless loop. The only way out is a hard kill -9
[mp00.log.gz](https://github.com/user-attachments/files/17351640/mp00.log.gz)

### Relevant MotionPlus log output (at log_level 8)

```shell
log file attached because of size
```

**Comment by sroller** [comment]
Upon further investigation I think this might be related to a "flakieness" on the part of the Raspberry Pis. I'm streaming using rpicam-vid/libcamera-vid and this setup is not stable. Sometimes it works, sometime it doesn't without any change in configuration. Extremely frustrating.

**Comment by axeljerabek** [comment]
I have about the same setup, streaming from several Rpi nodes to an x86_64 Ubuntu 24.04.1 and it works. One difference: I stream h264 that is directly encoded on the cam module and not the Rpis. so no mjpeg. Also i stream RTMP over nginx. The only "bug" I have there: the Cameras are not easily picked up by MPlus, so I have to wait a minute or two sometimes, although I can watch the streams instantly with VLC, for example. So the Stream detection in MPlus seems a bit more picky or slow. Sometimes I have to restart the streams from the Cams, that helps, but also needs 20 more seconds (probably the network/rtmp delay itself), but then it mostly works. OBS is also working immediately with the streams, only MP is a bit tricky sometimes.
Yes, I know that you are German speaking, but was writing in English since most people here speak E :)
Aber wenn du willst, schreib mir privat, evtl kann ich dir beim Debug helfen?

**Comment by sroller** [comment]
Hi Axel, I already sent an email to the email address listed on your github account a few days ago. Thank you for your help.

**Comment by axeljerabek** [comment]
> Hi Axel, I already sent an email to the email address listed on your github account a few days ago. Thank you for your help.

not in inbox?
